# Generated by Django 2.0.1 on 2018-07-21 07:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField()),
                ('menu_items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None)),
                ('time_stamp_entered', models.DateTimeField(auto_now_add=True)),
                ('order_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('time_stamp_entered',),
            },
        ),
    ]
